name: ruviel
description: A simple Instagram clone with UI only
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  http: ^1.1.0
  video_player: ^2.8.2
  shared_preferences: ^2.1.1
  image_picker: ^1.1.1
  image_picker_web: ^3.1.1
  supabase_flutter: ^2.5.5
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  timeago: ^3.6.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  video_player: ^2.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/reels/